name: Building

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: install node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: install java 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt-hotspot"
          java-version: "8"

      - name: install dependencies
        run: |
          npm install
          npm install -g turtle-cli

      - name: build
        run: turtle build:android
